# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee5a454aa4cab40ebb0f0d960d8e63f87b07aa04fcbee5ab4cb1e4147bbc9ed857ed251507bcfbd8c558f79bd64b0b93119de1e0baddcfed8b454f23c828ce54

test:
  secret_key_base: c4278272ea820b9d4706e91d04ab398c0eb5702dc1a78fd3c7be78bc3f3bef03011640088fe3b91af3d4460302ed8689ca405f5aebc9be06968d074b2c24c826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
